<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGpBocH9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGpBocH9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGpBocH9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGpBocH9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerGpBocH9\App_KernelProdContainer([
    'container.build_hash' => 'GpBocH9',
    'container.build_id' => 'b825a2a6',
    'container.build_time' => 1680503606,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGpBocH9');
