<?php

namespace ContainerGpBocH9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddFilmCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\AddFilmCommand' shared autowired service.
     *
     * @return \App\Command\AddFilmCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\AddFilmCommand'] = $instance = new \App\Command\AddFilmCommand($container);

        $instance->setName('app:add-film');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
