<?php

namespace ContainerGpBocH9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddCommentCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\AddCommentCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\AddCommentCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:add-comment', [], 'Add a short description for your command', false, function () use ($container): \App\Command\AddCommentCommand {
            return ($container->privates['App\\Command\\AddCommentCommand'] ?? $container->load('getAddCommentCommandService'));
        });
    }
}
