<?php

namespace ContainerGpBocH9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDelFilmCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\DelFilmCommand' shared autowired service.
     *
     * @return \App\Command\DelFilmCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\DelFilmCommand'] = $instance = new \App\Command\DelFilmCommand($container);

        $instance->setName('app:del-film');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
