<?php

namespace ContainerGpBocH9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilmControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FilmController' shared autowired service.
     *
     * @return \App\Controller\FilmController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FilmController'] = $instance = new \App\Controller\FilmController(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\FilmController', $container));

        return $instance;
    }
}
