<?php

namespace ContainerGpBocH9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListFilmsCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\ListFilmsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\ListFilmsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:list-films', [], 'Show the list of all the films.', false, function () use ($container): \App\Command\ListFilmsCommand {
            return ($container->privates['App\\Command\\ListFilmsCommand'] ?? $container->load('getListFilmsCommandService'));
        });
    }
}
