<?php

namespace ContainerGpBocH9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowFilmCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\ShowFilmCommand' shared autowired service.
     *
     * @return \App\Command\ShowFilmCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\ShowFilmCommand'] = $instance = new \App\Command\ShowFilmCommand($container);

        $instance->setName('app:show-film');
        $instance->setDescription('Show commentaires for a film.');

        return $instance;
    }
}
