<?php

namespace ContainerGpBocH9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowFilmCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\ShowFilmCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\ShowFilmCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:show-film', [], 'Show commentaires for a film.', false, function () use ($container): \App\Command\ShowFilmCommand {
            return ($container->privates['App\\Command\\ShowFilmCommand'] ?? $container->load('getShowFilmCommandService'));
        });
    }
}
