<?php

namespace ContainerTTPlxgo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListFilmsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ListFilmsCommand' shared autowired service.
     *
     * @return \App\Command\ListFilmsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ListFilmsCommand.php';

        $container->privates['App\\Command\\ListFilmsCommand'] = $instance = new \App\Command\ListFilmsCommand($container);

        $instance->setName('app:list-films');
        $instance->setDescription('Show the list of all the films.');

        return $instance;
    }
}
