<?php

namespace ContainerTTPlxgo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowFilmCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ShowFilmCommand' shared autowired service.
     *
     * @return \App\Command\ShowFilmCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ShowFilmCommand.php';

        $container->privates['App\\Command\\ShowFilmCommand'] = $instance = new \App\Command\ShowFilmCommand($container);

        $instance->setName('app:show-film');
        $instance->setDescription('Show commentaires for a film.');

        return $instance;
    }
}
